# Site Settings
title: Detflix
email: davsensan@gmail.com
description: Blog acerca de las nuevas tecnologías de desarrollo y/o telecomunicaciones
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davsensan.redirectme.net" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Blog DavSenSan
user_description: Gradudado en Ingeniería de Telecomunicaciones.
disqus_username: http-davsensan-redirectme-net

# Social Media
# Remove the item if you don't need it
github_username: davsensan
#facebook_username: David Señas Sanvicente
twitter_username: davsensan
instagram_username: davsensan
linkedin_username: davsensan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
  - title: Acerca de mí
    url: /about/
  - title: Contactar
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
